services:
  - type: web
    name: fingerprint-dashboard
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
