services:
  - type: web
    name: esp-a6-server
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node server.js"

    envVars:
      - key: PORT
        value: 80

    disk:
      name: data
      mountPath: /app
      sizeGB: 1
